export const FETCH_HITS_REQUEST = 'FETCH_HITS_REQUEST';
export const FETCH_HITS_FAILURE = 'FETCH_HITS_FAILURE';
export const FETCH_HITS_SUCCESS = 'FETCH_HITS_SUCCESS';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const CHANGE_CATEGORIES_CLASSNAME = 'CHANGE_CATEGORIES_CLASSNAME';

export const FETCH_CATALOG_ELEMENTS_REQUEST = 'FETCH_CATALOG_ELEMENTS_REQUEST';
export const FETCH_CATALOG_ELEMENTS_FAILURE = 'FETCH_CATALOG_ELEMENTS_FAILURE';
export const FETCH_CATALOG_ELEMENTS_SUCCESS = 'FETCH_CATALOG_ELEMENTS_SUCCESS';

export const FETCH_MORE_ELEMENTS_REQUEST = 'FETCH_MORE_ELEMENTS_REQUEST';
export const FETCH_MORE_ELEMENTS_FAILURE = 'FETCH_MORE_ELEMENTS_FAILURE';
export const FETCH_MORE_ELEMENTS_SUCCESS = 'FETCH_MORE_ELEMENTS_SUCCESS';

export const FETCH_ELEMENT_REQUEST = 'FETCH_ELEMENT_REQUEST';
export const FETCH_ELEMENT_FAILURE = 'FETCH_ELEMENT_FAILURE';
export const FETCH_ELEMENT_SUCCESS = 'FETCH_ELEMENT_SUCCESS';

export const SELECT_SIZE = 'SELECT_SIZE';

export const INCREASE_THE_NUMBER = 'INCREASE_THE_NUMBER';
export const DECREASE_THE_NUMBER = 'DECREASE_THE_NUMBER';
export const DEFAULT_THE_NUMBER = 'DEFAULT_THE_NUMBER';

export const TOGGLE_CLASSNAME = 'TOGGLE_CLASSNAME';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';

export const CHANGE_FIELD = 'CHANGE_FIELD';

export const DELAY_SEARCH = 'DELAY_SEARCH';

export const SENDING_TO_CART = 'SENDING_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const EMPTY_CART = 'EMPTY_CART';

export const SEND_AN_ORDER_REQUEST = 'SEND_AN_ORDER_REQUEST';
export const SEND_AN_ORDER_FAILURE = 'SEND_AN_ORDER_FAILURE';
export const SEND_AN_ORDER_SUCCESS = 'SEND_AN_ORDER_SUCCESS';
