export const FETCH_HITS_REQUEST = 'FETCH_HITS_REQUEST';
export const FETCH_HITS_FAILURE = 'FETCH_HITS_FAILURE';
export const FETCH_HITS_SUCCESS = 'FETCH_HITS_SUCCESS';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const FETCH_CATALOG_ELEMENTS_REQUEST = 'FETCH_CATALOG_ELEMENTS_REQUEST';
export const FETCH_CATALOG_ELEMENTS_FAILURE = 'FETCH_CATALOG_ELEMENTS_FAILURE';
export const FETCH_CATALOG_ELEMENTS_SUCCESS = 'FETCH_CATALOG_ELEMENTS_SUCCESS';

export const CHANGE_CATEGORIES_CLASSNAME = 'CHANGE_CATEGORIES_CLASSNAME';
 
